const INITIAL_STATUS = 0;
const START_DISCUSSION = 1;
const START_ESTIMATION = 2;
const END_ESTIMATION = 3;

export default {
  INITIAL_STATUS,
  START_DISCUSSION,
  START_ESTIMATION,
  END_ESTIMATION,
};
